[package]
name = "face"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24.3"
imageproc = "0.23.0"
rustface = "0.1.7"
uuid = { version = "1.1.2", features = ["v4"] }

